export const CategoriesData = [
    {
      id: 1,
      name: "Vehicles",
      image: "/f8.avif",
      status: "Active",
      subcategories: [
        {
          id: 1,
          name: "Cars",
          image: "/img1.png",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 2,
          name: "Motorcycle",
          image: "/img2.png",
          status: "Inactive",
          Datecreated: "12-7-2024",
        },
        {
          id: 3,
          name: "Truck",
          image: "/img3.png",
          status: "Inactive",
          Datecreated: "12-7-2024",
        },
        {
          id: 4,
          name: "Bike",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 5,
          name: "Boat",
          image: "/f8.avif",
          status: "Inactive",
          Datecreated: "12-7-2024",
        },
        {
          id: 6,
          name: "Van",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 7,
          name: "Scooter",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 8,
          name: "Parts and Accessories",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
      ],
    },
    {
      id: 2,
      name: "Real Estate",
      image: "/f12.avif",
      status: "Active",
      subcategories: [
        {
          id: 1,
          name: "House",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 2,
          name: "Apartment",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 3,
          name: "Land",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 4,
          name: "Mobile Home",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 5,
          name: "Bedroom",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 6,
          name: "Suite",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 7,
          name: "Studio",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 8,
          name: "Vacation Home",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 9,
          name: "Basement",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
      ],
    },
    {
      id: 3,
      name: "Services",
      image: "/f13.avif",
      status: "Active",
      subcategories: [
        {
          id: 1,
          name: "Cleaning",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 2,
          name: "Handyman",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 3,
          name: "Drivers",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 4,
          name: "Landscaping",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 5,
          name: "Consultancy",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 6,
          name: "Home Automation",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 7,
          name: "Classes & Courses",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 8,
          name: "Personal Training",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 9,
          name: "Construction",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 10,
          name: "Technology",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 11,
          name: "Immigration and Visa",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 12,
          name: "Event Services",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 13,
          name: "Movers & Packers",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 14,
          name: "Farm & Fresh Food",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 15,
          name: "Video & Photography",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 16,
          name: "Interior Design",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 17,
          name: "Homemade Food",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 18,
          name: "Insurance Services",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 19,
          name: "Home Care ( Health)",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 20,
          name: "Catering",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 21,
          name: "Chef",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 22,
          name: "Influencer",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 23,
          name: "AC Services",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 24,
          name: "Personal Trainer",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 25,
          name: "Cake",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 26,
          name: "Finger Food",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 27,
          name: "Buffetr",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 28,
          name: "Transport Services",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
      ],
    },
    {
      id: 4,
      name: "Events",
      image: "/f7.avif",
      status: "Active",
      subcategories: [
        {
          id: 1,
          name: "Networking Events",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 2,
          name: "Concert",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 3,
          name: "Festival",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
      ],
    },
    {
      id: 5,
      name: "jobs",
      image: "/f3.avif",
      status: "Active",
      subcategories: [
        {
          id: 1,
          name: "Full Time",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 2,
          name: "Part Time",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 3,
          name: "Freelancer",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 4,
          name: "Helper",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 5,
          name: "Home Office",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
      ],
    },
    {
      id: 6,
      name: "Electronics",
      image: "/f1.webp",
      status: "Active",
      subcategories: [
        {
          id: 1,
          name: "Smartphones",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 2,
          name: "Computers",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 3,
          name: "Appliances",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 4,
          name: "Games",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 5,
          name: "Services & Parts",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
      ],
    },
    {
      id: 7,
      name: "Furniture",
      image: "/f2.webp",
      status: "Active",
      subcategories: [
        {
          id: 1,
          name: "Couch",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 2,
          name: "Tables",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 3,
          name: "Chairs",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 4,
          name: "Beds",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 5,
          name: "Custom Furniture",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
      ],
    },
    {
      id: 8,
      name: "Fashion",
      image: "/f7.avif",
      status: "Active",
      subcategories: [
        {
          id: 1,
          name: "Clothes",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 2,
          name: "Shoes",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 3,
          name: "Accessories",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 4,
          name: "Beauty Products",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 5,
          name: "Jewelry",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
      ],
    },
    {
      id: 9,
      name: "Kids",
      image: "/f5.avif",
      status: "Active",
      subcategories: [
        {
          id: 1,
          name: "Health",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 2,
          name: "Toys",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 3,
          name: "Transport",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 4,
          name: "Accessories",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 5,
          name: "Classes",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 6,
          name: "Babysitter",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 7,
          name: "Daycare",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 8,
          name: "School Offices",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 9,
          name: "Afterschool Program",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 10,
          name: "Activities",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
      ],
    },
    {
      id: 10,
      name: "Sports & Hobby",
      image: "/f6.avif",
      status: "Active",
      subcategories: [
        {
          id: 1,
          name: "Sports Equipment",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 2,
          name: "Musical Instruments ",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 3,
          name: "Collected Items",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 4,
          name: "Games",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 5,
          name: "Camping",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
        {
          id: 6,
          name: "Outdoor Activities",
          image: "/f8.avif",
          status: "Active",
          Datecreated: "12-7-2024",
        },
      ],
    },
  ];
  