export const UserData = [

    {
        "ID": "352",
        "Email": "user@example.com",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Active",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
      },
      {
        "ID": "352",
        "Email": "user@example.com",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Active",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
      },
      {
        "ID": "352",
        "Email": "user@example.com",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Inactive",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
      },
      {
        "ID": "352",
        "Email": "user@example.com",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Deleted",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
      },
      {
        "ID": "352",
        "Email": "user@example.com",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Inactive",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
      },
      {
        "ID": "352",
        "Email": "user@example.com",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Deleted",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
      },{
        "ID": "352",
        "Email": "user@example.com",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Deleted",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
      },
      {
        "ID": "353",
        "Email": "user@example.com",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Active",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
      },
      {
        "ID": "354",
        "Email": "user@example.com",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Active",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
      },
      {
        "ID": "355",
        "Email": "user@example.com",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Active",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
      },
      {
        "ID": "356",
        "Email": "user@example.com",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Active",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
      }
    ]
    
    export  const getHeaderStyle = () => {
        return { fontSize: '14px', 
                  fontweigh: '800',
                  textalign: 'center',
                  color:'#757575',
                  fontFamily:"plus",
                  padding:"25px",
                  background:"#F5F7F9",
                  
      
                  
        }; 
    };
    export  const getBodyStyle = () => {
        return { fontSize: '14px', 
                  fontweigh: '800',
                  color:'#78828A',
                  paddingLeft:'25px',
                  paddingTop:'25px',
                  fontFamily:"plus",
                  textalign: 'center',
    
                          
        }; 
    }; 