export const BusniessData = [
    {
        "ID": "352",
        "Email": "user@example.com",
        "BusinessName": "braelo",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Active",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
        "website": "https://wa.me/000",
        "BusinessType":"Business Type",
      },
      {
        "ID": "352",
        "Email": "user@example.com",
        "BusinessName": "braelo",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Active",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
        "website": "https://wa.me/000",
        "BusinessType":"Business Type",
      },  {
        "ID": "352",
        "Email": "user@example.com",
        "BusinessName": "braelo",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Active",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
        "website": "https://wa.me/000",
        "BusinessType":"Business Type",
      },  {
        "ID": "352",
        "Email": "user@example.com",
        "BusinessName": "braelo",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Active",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
        "website": "https://wa.me/000",
        "BusinessType":"Business Type",
      },  {
        "ID": "352",
        "Email": "user@example.com",
        "BusinessName": "braelo",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Active",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
        "website": "https://wa.me/000",
        "BusinessType":"Business Type",
      },  {
        "ID": "352",
        "Email": "user@example.com",
        "BusinessName": "braelo",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Active",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
        "website": "https://wa.me/000",
        "BusinessType":"Business Type",
      },  {
        "ID": "352",
        "Email": "user@example.com",
        "BusinessName": "braelo",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Active",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
        "website": "https://wa.me/000",
        "BusinessType":"Business Type",
      },  {
        "ID": "352",
        "Email": "user@example.com",
        "BusinessName": "braelo",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Active",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
        "website": "https://wa.me/000",
        "BusinessType":"Business Type",
      },  {
        "ID": "352",
        "Email": "user@example.com",
        "BusinessName": "braelo",
        "Google ID": "google-987654",
        "Apple ID": "apple-654321",
        "Phone Number": "+1234567890",
        "Full Name": "Jane Deo",
        "Password": "Aleeoomm@ok",
        "Status": "Active",
        "Email Verified": "Verified",
        "Phone Verified": "Unverified",
        "Date Created": "06/15/2024",
        "Last Update": "07/12/2024",
        "Role": "User",
        "OTP": "123456",
        "Device Token": "123Addd",
        "Total Listings": 10,
        "Active Listings": 7,
        "Deleted Listings": 3,
        "EmailVerified": "Verified",
        "PhoneVerified": "Unverified",
        "website": "https://wa.me/000",
        "BusinessType":"Business Type",
      },
]